name: Prolog CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar SWI-Prolog
        run: sudo apt-get update && sudo apt-get install -y swi-prolog

      - name: Rodar Testes
        run: |
          